config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'dashboard#version2'
  get 'dashboard2' => 'dashboard#index', as: :dashboard

  get 'upload' => 'upload#index', as: :upload

  resources :orders do
    collection { post :import_etsy }
    collection { post :import_square }
  end
  get 'wholesale_orders' => 'orders#wholesale', as: :wholesale

  resources :order_items do
    collection { post :import_etsy }
    collection { post :import_square }
  end

  resources :expenses do
    collection { post :import }
  end

  resources :products
  resources :customers
  resources :listings
  resources :variations
  resources :giveaways

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  #######################################################
  # Specifies Associations
  # Read more about Rails Associations here: http://guides.rubyonrails.org/association_basics.html
  belongs_to :product
  belongs_to :variation
  has_many :listings

  #######################################################
  # Makes it so that when you print the object, you print a display name instead of the "#<ActiveRecord>blahblah" object name
  alias_attribute :name, :etsy_listing_variation

  #######################################################
  # Makes it so that you can edit these database columns via ActiveAdmin and forms
  attr_accessible :listing_type, :etsy_listing_variation, :product_id, :variation_id, :item_name

  def get_order_items
    @order_items = OrderItem.where(etsy_listing_variation: self.etsy_listing_variation)
  end

end

app/views/listings/index.html.haml
#page-listings.page-content-body
  .page-content-body-section
    %h1 Listings

    %table#table-listings.stripe.order-column
      %thead
        %tr
          %th Type
          %th Item
          %th Style
          %th Gender
          %th Color
          %th Size
          %th Listing
      %tbody
        - get_listings.each do |listing|
          %tr
            %td
              = listing.product.product_type.product_type
            %td.border-right=listing.product.description
            - if listing.variation
              %td
                = listing.variation.product_type.product_type
                = listing.variation.style
              %td=listing.variation.gender
              %td=listing.variation.color
              %td.border-right=listing.variation.size
            - else
              %td
              %td
              %td
              %td.border-right
            %td
              =listing.etsy_listing_variation
              = link_to edit_admin_listing_url(listing) do
                %span.glyphicon.glyphicon-pencil.edit-icon

:javascript
  $("#table-listings").DataTable({
    dom: 'iCfrtS',
    pageLength: -1,
    order: [0, 'asc'],
    orderClasses: true
  });