config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'dashboard#version2'
  get 'dashboard2' => 'dashboard#index', as: :dashboard

  get 'upload' => 'upload#index', as: :upload

  resources :orders do
    collection { post :import_etsy }
    collection { post :import_square }
  end
  get 'wholesale_orders' => 'orders#wholesale', as: :wholesale

  resources :order_items do
    collection { post :import_etsy }
    collection { post :import_square }
  end

  resources :expenses do
    collection { post :import }
  end

  resources :products
  resources :customers
  resources :listings
  resources :variations
  resources :giveaways

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  #######################################################
  # Specifies Associations
  # Read more about Rails Associations here: http://guides.rubyonrails.org/association_basics.html
  has_many :orders

  #######################################################
  # Makes it so that when you print the object, you print a display name instead of the "#<ActiveRecord>blahblah" object name
  alias_attribute :name, :etsy_username

  #######################################################
  # Makes it so that you can edit these database columns via ActiveAdmin and forms
  attr_accessible *column_names

  def display_name
    if etsy_username
      "#{first_name} #{last_name} (#{etsy_username})"
    else
      "#{first_name} #{last_name}"
    end
  end

  def get_first_purchase_date
    order = Order.where(customer: self).order(sale_date: :asc).first
    if order
      order.sale_date
    else
      nil
    end
  end

  def get_last_purchase_date
    order = Order.where(customer: self).order(sale_date: :desc).first
    if order
      order.sale_date
    else
      nil
    end
  end

  def get_orders
    orders = Order.where(customer: self)
  end

  def get_unshipped_orders_count
    unshipped_orders = Order.where(customer: self, date_shipped: nil).count
  end

  def get_order_items
    OrderItem.joins(:order).where(orders: {customer: self})
  end

  def get_total_order_count
    get_orders.count
  end

  def get_total_order_items_count
    get_orders.sum(:number_of_items)
  end

  def get_total_spend
    # Accounts for fees
    (get_orders.sum(:order_net) - get_orders.sum(:refund)).round(2)
  end

  def get_average_items_per_order
    (get_total_order_items_count/get_total_order_count).round(2)
  end

  def get_average_spend_per_order
    (get_total_spend/get_total_order_count).round(2)
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @total_customers = Customer.count
    @customers = Customer.all
  end

  def show
    @customer = Customer.find_by_id(params[:id])
    @orders = Order.where(customer: @customer)
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
  def get_customers(customer_type=nil)
    if customer_type
      Customer.where(customer_type: customer_type)
    else
      Customer.all
    end
  end

  # Customer Count ##########
  def get_customers_count(customer_type=nil, start_date=nil, end_date=nil)
    if start_date == nil 
      start_date = get_first_sale_date(customer_type)
    end
    if end_date == nil
      end_date = get_last_sale_date(customer_type)
    end
    if customer_type
      return Order.where(order_type: customer_type, sale_date: start_date..end_date).pluck(:customer_id).uniq.count
    else
      return Order.where(sale_date: start_date..end_date).pluck(:customer_id).uniq.count
    end
  end
  def get_customers_count_by_month(customer_type=nil, month)
    start_date = Date.new(month.year, month.month, 1)
    end_date = Date.civil(month.year, month.month, -1)
    return get_customers_count(customer_type, start_date, end_date)
  end
  def get_customers_count_by_year(customer_type=nil, year)
    start_date = Date.new(year, 1, 1)
    end_date = Date.civil(year, 12, -1)
    return get_customers_count(customer_type, start_date, end_date)
  end

end

app/views/customers/index.html.haml
#page-customers.page-content-body
  .page-content-body-section
    %h1 Wholesale Customers

    .stats
      .stat-container
        .stat
          .stat-label Total Customers
          .stat-number
            = get_customers_count("Wholesale")
            customers
      .stat-container
        .stat
          .stat-label Average Rev Per Customer
          .stat-number
            = "$" + get_average_revenue_per_customer("Wholesale", nil, nil).to_s + "/customer"
      .stat-container
        .stat
          .stat-label Average Orders Per Customer
          .stat-number
            = get_average_orders_per_customer("Wholesale").to_s + "/customer"
      .stat-container
        .stat
          .stat-label Average Order Items Per Customer
          .stat-number
            = get_average_order_items_per_customer("Wholesale").to_s + "/customer"

    %table#table-wholesale-customers.stripe.order-column
      %thead
        %tr
          %th Name
          %th Company
          %th Instagram
          %th Source
          %th First Purchase
          %th Last Purchase
          %th Orders
          %th Items
          %th Spend
      %tbody
        - get_customers("Wholesale").each do |customer|
          %tr
            %td.border-right
              = link_to customer_url(customer) do
                = customer.first_name
                = customer.last_name
              = link_to edit_admin_customer_url(customer) do
                %span.glyphicon.glyphicon-pencil.edit-icon
            %td.border-right= customer.company
            %td.border-right
              - if customer.instagram
                %a{href: "http://www.instagram.com/" + customer.instagram, target: "_blank"}
                  = customer.instagram
            %td.border-right= customer.source
            %td= customer.get_first_purchase_date
            %td.border-right= customer.get_last_purchase_date
            %td= customer.get_total_order_count
            %td= customer.get_total_order_items_count
            %td= "$" + customer.get_total_spend.to_s


  .page-content-body-section
    %h1 Retail Customers

    .stats
      .stat-container
        .stat
          .stat-label Total Customers
          .stat-number
            = get_customers_count("Retail")
            customers
      .stat-container
        .stat
          .stat-label Average Rev Per Customer
          .stat-number
            = "$" + get_average_revenue_per_customer("Retail", nil, nil).to_s + "/customer"
      .stat-container
        .stat
          .stat-label Average Orders Per Customer
          .stat-number
            = get_average_orders_per_customer("Retail").to_s + "/customer"
      .stat-container
        .stat
          .stat-label Average Order Items Per Customer
          .stat-number
            = get_average_order_items_per_customer("Retail").to_s + "/customer"

    %table#table-retail-customers.stripe.order-column
      %thead
        %tr
          %th Name
          %th Etsy Username
          %th Instagram
          %th Source
          %th First Purchase
          %th Last Purchase
          %th Orders
          %th Items
          %th Spend
      %tbody
        - get_customers("Retail").each do |customer|
          %tr
            %td.border-right
              = link_to customer_url(customer) do
                = customer.first_name
                = customer.last_name
              = link_to edit_admin_customer_url(customer), target: "_blank" do
                %span.glyphicon.glyphicon-pencil.edit-icon
            %td.border-right= customer.etsy_username
            %td.border-right
              - if customer.instagram
                %a{href: "http://www.instagram.com/" + customer.instagram, target: "_blank"}
                  = customer.instagram
            %td.border-right= customer.source
            %td= customer.get_first_purchase_date
            %td.border-right= customer.get_last_purchase_date
            %td= customer.get_total_order_count
            %td= customer.get_total_order_items_count
            %td= "$" + customer.get_total_spend.to_s



:javascript
  $("#table-wholesale-customers").DataTable({
    dom: 'iCfrtS',
    pageLength: -1,
    order: [6, 'desc'],
    orderClasses: true
  });

  $("#table-retail-customers").DataTable({
    dom: 'iCfrtS',
    pageLength: -1,
    order: [5, 'desc'],
    orderClasses: true
  });

app/views/customers/show.html.haml
.page-customer.page-content-body{class: "#page-customer-" + @customer.id.to_s}
  .page-content-body-section
    .page-navigation
      = link_to customers_url do
        « Back to customers
    %h1.order-title
      =link_to customer_url(@customer) do
        = @customer.first_name
        = @customer.last_name
        = "(" + @customer.etsy_username + ")"

      =link_to edit_admin_customer_url(@customer), target: "_blank" do
        %span.glyphicon.glyphicon-pencil.edit-icon
      .order-title-tagline
        =@customer.customer_type
        - if !@customer.source.nil?
          = " - " + @customer.source.to_s

  .page-content-body-section-box
    %table.customer-table
      %tr
        %td
          %span.customer-table-label Total Orders
          %span.customer-table-info= @customer.get_total_order_count
          %br
          %br
          %span.customer-table-label Unshipped Orders
          %span.customer-table-info.red= @customer.get_unshipped_orders_count
        %td.border-right
          %span.customer-table-label Total Items
          %span.customer-table-info
            = @customer.get_total_order_items_count
            items
          %br
          %br
          %span.customer-table-label Average Items
          %span.customer-table-info
            = @customer.get_average_items_per_order
            items/order
        %td.border-right
          %span.customer-table-label Total Revenue
          %span.customer-table-info.customer-table-net= "$" + @customer.get_total_spend.to_s
          %br
          %span.customer-table-label Average Revenue
          %span.customer-table-info
            = "$" + @customer.get_average_spend_per_order.to_s + "/order"
        %td.border-right
          %span.customer-table-label First Purchase
          %span.customer-table-info= @customer.get_first_purchase_date
          %br
          %br
          %span.customer-table-label Last Purchase
          %span.customer-table-info= @customer.get_last_purchase_date
        %td
          %span.customer-table-label
            =link_to customer_url(@customer) do
              = @customer.first_name + " " + @customer.last_name
            - if @customer.company != ""
              %br
              = @customer.company
              %br
          %span.customer-table-info.secondary
            = "(" + @customer.etsy_username + ")"
            %br
          - if @customer.email
            %a{href: "mailto:" + @customer.email}
              = @customer.email
            %br
          - if @customer.instagram != "" || @customer.instagram != nil
            %a{href: "http://www.instagram.com/" + @customer.instagram.to_s}
              = "@" + @customer.instagram.to_s
            %br
        %td
          %span.customer-table-label Shipping Address
          %span.customer-table-info
            = @customer.ship_name
            %br
            = @customer.ship_address1
            %br
            - if @customer.ship_address2 != "" || @customer.ship_address2 != nil
              = @customer.ship_address2
              %br
            = @customer.ship_city + ", " + @customer.ship_state + " " + @customer.ship_zipcode
            %br
            = @customer.ship_country

  .page-content-body-section
    %table#table-customer-orders.stripe.order-column
      %thead
        %tr
          %th Order
          %th Sold
          %th Shipped
          %th Items
          %th Value
          %th Coupon
          %th Shipping
          %th Tax
          %th Refund
          %th Total
          %th Fee
          %th Net
          %th Payment
      %tbody
        - @orders.each do |order|
          %tr
            %td.border-right
              %span.order-number
                = link_to order_url(order) do
                  - if order.order_number != ""
                    = order.order_number 
                  - else
                    = order.id
            %td= order.sale_date
            %td.border-right
              - if order.date_shipped
                = order.date_shipped
              - else
                %span.red Unshipped
            %td.border-right= order.number_of_items
            %td= "$" + order.order_value.to_s
            %td
              = order.coupon_code
              %span.secondary= order.coupon_details
            %td= "$" + order.shipping.to_s
            %td= "$" + order.sales_tax.to_s
            %td.border-right= order.refund? ? "$" + order.refund.to_s : ""
            %td
              = order.refund? ? "$" + order.adjusted_order_total.to_s : "$" + order.order_total.to_s
            %td
              = order.adjusted_card_processing_fees? ? "$" + order.adjusted_card_processing_fees.to_s : "$" + order.card_processing_fees.to_s
            %td.border-right
              = order.refund? ? "$" + order.adjusted_net_order_amount.to_s : "$" + order.order_net.to_s
            %td
              %span.secondary= order.payment_type + " - " + order.order_source
  

          

:javascript
  $("#table-customer-orders").DataTable({
    dom: 'iCfrtS',
    pageLength: -1,
    order: [1, 'desc'],
    orderClasses: true
  });