config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'dashboard#version2'
  get 'dashboard2' => 'dashboard#index', as: :dashboard

  get 'upload' => 'upload#index', as: :upload

  resources :orders do
    collection { post :import_etsy }
    collection { post :import_square }
  end
  get 'wholesale_orders' => 'orders#wholesale', as: :wholesale

  resources :order_items do
    collection { post :import_etsy }
    collection { post :import_square }
  end

  resources :expenses do
    collection { post :import }
  end

  resources :products
  resources :customers
  resources :listings
  resources :variations
  resources :giveaways

end

app/models/order.rb
class Order < ActiveRecord::Base

  #######################################################
  # Specifies Associations
  # Read more about Rails Associations here: http://guides.rubyonrails.org/association_basics.html
  belongs_to :customer
  has_many :order_items

  #######################################################
  # Makes it so that when you print the object, you print a display name instead of the "#<ActiveRecord>blahblah" object name
  alias_attribute :name, :order_number

  #######################################################
  # Makes it so that you can edit these database columns via ActiveAdmin and forms
  attr_accessible *column_names

  def display_name
    customer = Customer.find_by_id(self.customer_id)
    if customer
      return self.sale_date.to_s + ' - ' + self.order_number.to_s + ' - ' + customer.display_name.to_s
    else
      return self.sale_date.to_s + ' - ' + self.order_number.to_s
    end
  end

  def self.import_etsy(file)
    CSV.foreach(file.path, headers:true) do |row|
      order = Order.find_by(order_number: row[1])

      if row[1].include? "PO"
        customer_type = "Wholesale"
      else
        customer_type = "Retail"
      end

      customer = Customer.find_by(etsy_username: row[2])
      if !(customer)
        customer = Customer.create({
            :first_name=> row[4],
            :last_name=> row[5],
            :etsy_username=> row[2],
            :ship_name=> row[3],
            :ship_address1=> row[9],
            :ship_address2=> row[10],
            :ship_city=> row[11],
            :ship_state=> row[12],
            :ship_zipcode=> row[13],
            :ship_country=> row[14],
            :customer_type=> customer_type
          })
      end

      #set payment_type and payment_method
      payment_method = row[7]
      if row[30] == "cash"
        payment_type = "In Person"
        payment_method = "Cash"
      elsif row[30] == "online_cc"
        payment_type = "Online"
      elsif row[30] == "swipe"
        payment_type = "In Person"
      else
        payment_method = "Other"
        payment_type = "Other"
      end

      #set order_type
      order_number = row[1]
      if order_number.include? "PO"
        order_type = "Wholesale"
      else
        order_type = "Retail"
      end

      order_params = {
        #date_paid is marked by order item upload
        :sale_date=> (DateTime.strptime row[0], "%m/%d/%y").strftime("%Y/%m/%d"),
        :order_number=> row[1],
        :username=> row[2],
        :full_name=> row[3],
        :first_name=> row[4],
        :last_name=> row[5],
        :number_of_items=> row[6],
        :payment_method=> payment_method,
        :date_shipped=> row[8].nil? ? nil : DateTime.strptime(row[8], "%m/%d/%y").strftime("%Y/%m/%d"),
        :currency=> row[15],
        :order_value=> row[16],
        :coupon_code=> row[17],
        :coupon_details=> row[18],
        :shipping=> row[21],
        :sales_tax=> row[22],
        :order_total=> row[23],
        :card_processing_fees=> row[25],
        :order_net=> row[26],
        :adjusted_order_total=> row[27],
        :adjusted_card_processing_fees=> row[28],
        :adjusted_net_order_amount=> row[29],
        :order_type=> order_type,
        :payment_type=> payment_type,
        :inperson_discount=> row[33],
        :inperson_location=> row[34],
        :order_source=> "Etsy",
        :customer_id=>customer.id,
        :refund=> row[27].nil? ? nil : (row[23].to_f - row[27].to_f).round(2)
      }

      if (order)
        order.update(order_params)
      else
        order = Order.create(order_params)
      end

      order.save!
    end
  end

  def self.import_square(file)
    CSV.foreach(file.path, headers:true) do |row|
      order = Order.find_by(order_number: row[21])

      square_username = "sq_" + row[21]
      customer = Customer.find_by(etsy_username: square_username)
      if !(customer)
        customer = Customer.create({
            :etsy_username=> square_username,
            :first_name=> "Square",
            :last_name=> "Customer"
          })
      end

      if row[11].delete('$').to_f != 0
        payment_method = "Credit Card"
      elsif row[12].delete('$').to_f != 0
        payment_method = "Credit Card"
      elsif row[13].delete('$').to_f != 0
        payment_method = "Cash"
      elsif row[14].delete('$').to_f != 0
        payment_method = "Wallet"
      elsif row[15].delete('$').to_f != 0
        payment_method = "Square Gift Card"
      end

      if row[30] == "Refund"
        refund = row[10].delete('$').to_f
        if order
          order_params = {
            :adjusted_order_total=> order.order_total + refund,
            :adjusted_net_order_amount=> order.order_net + refund,
            :refund=> refund.abs
          }
        end
      else
        order_params = {
          :sale_date=> (DateTime.strptime row[0], "%m/%d/%y").strftime("%Y/%m/%d"),
          :date_paid=> (DateTime.strptime row[0], "%m/%d/%y").strftime("%Y/%m/%d"),
          :order_number=> row[21],
          :username=> square_username,
          :full_name=> "Square Customer",
          :first_name=> "Square",
          :last_name=> "Customer",
          :payment_method=> payment_method,
          :order_value=> row[3].delete('$').to_f,
          :shipping=> "0.0",
          :sales_tax=> row[7].delete('$').to_f,
          :order_total=> row[5].delete('$').to_f,
          :card_processing_fees=> row[19].delete('$').to_f.abs,
          :order_net=> row[20].delete('$').to_f,
          :order_type=>"Retail",
          :payment_type=>"In Person",
          :order_source=> "Square",
          :customer_id=>customer.id,
          :date_shipped=> (DateTime.strptime row[0], "%m/%d/%y").strftime("%Y/%m/%d"),
          :coupon_code=> row[4] == "$0.00" ? nil : row[4],
          :inperson_discount=> row[4].delete('$').to_f
        }
      end

      if (order)
        order.update(order_params)
      else
        order = Order.create(order_params)
      end

      order.save!
    end
  end



  def get_order_items
    OrderItem.where(order: self)
  end




end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
    @order = Order.find_by_id(params[:id])
    @order_items = OrderItem.where(order: @order)
  end

  def wholesale
  end

  def new
    @order_types = Order.order(:order_type).uniq.pluck(:order_type)
    @payment_types = Order.order(:payment_type).uniq.pluck(:payment_type)
    @payment_methods = Order.order(:payment_method).uniq.pluck(:payment_method)
    @order_sources = Order.order(:order_source).uniq.pluck(:order_source)

    @order = Order.new({
      sale_date: Date.today,
      date_shipped: nil,
      currency: "USD",
      shipping: "0",
      sales_tax: "0",
      payment_method: "Cash"
    })
    @customers = Customer.all.order(:first_name)
  end

  def create
    order_params = params[:order]
    order_params[:order_net] = params[:order][:order_total]
    @order = Order.new(order_params)

    if @order.save
      redirect_to new_order_item_path, alert: "Order created successfully. Add your order items."
    else
      redirect_to new_order_path, alert: "Error creating order."
    end
  end

  def import_etsy
    Order.import_etsy(params[:file])
    redirect_to upload_path, notice: "Orders imported. Upload your order items now."
  end

  def import_square
    Order.import_square(params[:file])
    redirect_to upload_path, notice: "Orders imported. Upload your order items now."
  end

end

app/helpers/orders_helper.rb
module OrdersHelper

  # Orders
  def get_orders(order_type=nil, start_date=nil, end_date=nil)
    if start_date == nil 
      start_date = get_first_sale_date(order_type)
    end
    if end_date == nil
      end_date = get_last_sale_date(order_type)
    end
    if order_type
      Order.where(order_type: order_type, sale_date: start_date..end_date)
    else
      Order.where(sale_date: start_date..end_date)
    end
  end
  def get_orders_count(order_type=nil, start_date=nil, end_date=nil)
    get_orders(order_type, start_date, end_date).count
  end
  def get_orders_count_by_month(order_type=nil, month)
    start_date = Date.new(month.year, month.month, 1)
    end_date = Date.civil(month.year, month.month, -1)
    return get_orders_count(order_type, start_date, end_date)
  end
  def get_orders_count_by_year(order_type=nil, year)
    start_date = Date.new(year, 1, 1)
    end_date = Date.civil(year, 12, -1)
    return get_orders_count(order_type, start_date, end_date)
  end

  # Incomplete Orders
  def get_incomplete_orders_count(order_type=nil)
    get_unshipped_orders_count(order_type) + get_unpaid_orders_count(order_type)
  end


  # Unshipped Orders
  def get_unshipped_orders(order_type=nil)
    if order_type
      Order.where(order_type: order_type, date_shipped: nil).where.not(date_paid: nil)
    else
      Order.where(date_shipped: nil)
    end
  end
  def get_unshipped_orders_count(order_type=nil)
    get_unshipped_orders(order_type).count
  end


  # Completed Orders
  def get_completed_orders(order_type=nil)
    if order_type
      Order.where(order_type: order_type).where.not(date_shipped: nil, date_paid: nil)
    else
      Order.where.not(date_shipped: nil, date_paid: nil)
    end
  end

  # Unpaid Orders
  def get_unpaid_orders(order_type=nil)
    if order_type
      Order.where(order_type: order_type, date_paid: nil)
    else
      Order.where(date_paid: nil)
    end
  end
  def get_unpaid_orders_count(order_type=nil)
    get_unpaid_orders(order_type).count
  end

end

app/views/orders/index.html.haml
= render partial: 'orders', locals: {order_type: "Retail"}

app/views/orders/new.html.haml
#page-orders.page-content-body
  .page-content-body-section
    %h1 New Order


    =form_for(@order) do |f|
      .form-row
        = f.label :customer, class: 'form-label'
        = f.collection_select(:customer_id, @customers, :id, :display_name, {:prompt => true}, {:required => true})
        %span.form-notes 
          =link_to "Create new customer", new_admin_customer_path, target: "_blank"
      
      %br

      .form-row
        = f.label :sale_date, class: 'form-label'
        = f.date_field(:sale_date)
      .form-row
        = f.label :date_shipped, class: 'form-label'
        = f.date_field(:date_shipped)
      .form-row
        = f.label :date_paid, class: 'form-label'
        = f.date_field(:date_paid)

      %br

      .form-row
        = f.label :number_of_items, class: 'form-label'
        = f.number_field(:number_of_items)

      %br

      .form-row
        = f.label :order_value, class: 'form-label'
        = f.number_field :order_value, :step => 'any', :required => true
      .form-row
        = f.label :shipping, class: 'form-label'
        = f.number_field :shipping, :step => 'any'

      .form-row
        = f.label :sales_tax, class: 'form-label'
        = f.number_field :sales_tax, :step => 'any'

      .form-row
        = f.label :order_total, class: 'form-label'
        = f.number_field :order_total, :step => 'any', :required => true
        %span.form-notes = order value + shipping + sales tax

      %br

      .form-row
        = f.label :order_type, class: 'form-label'
        = f.select :order_type, @order_types
      .form-row
        = f.label :payment_type, class: 'form-label'
        = f.select :payment_type, @payment_types
      .form-row
        = f.label :payment_method, class: 'form-label'
        = f.select :payment_method, @payment_methods
      .form-row
        = f.label :order_source, class: 'form-label'
        = f.select :order_source, @order_sources
      


      .form-row
        = f.submit "Create Order"

app/views/orders/show.html.haml
.page-order.page-content-body{class: "#page-order-" + @order.id.to_s}
  .page-content-body-section
    .page-navigation
      - if @order.order_type == "Wholesale"
        = link_to wholesale_path do
          « Back to wholesale orders
      - else
        = link_to orders_path do
          « Back to retail orders
    %h1.order-title
      = @order.sale_date
      - if @order.order_number != ""
        = " - " + @order.order_number.to_s
      - else
        = " - " + @order.id.to_s
      =link_to customer_url(@order.customer) do
        = " - " + @order.customer.first_name + " " + @order.customer.last_name
      =link_to edit_admin_order_url(@order), target: "_blank" do
        %span.glyphicon.glyphicon-pencil.edit-icon
      .order-title-tagline
        =@order.order_type

  .page-content-body-section-box
    %table.order-table
      %tr
        %td.border-right{width: 135}
          %span.order-table-label Order Number
          %span.order-table-info
            =link_to order_url(@order) do
              - if @order.order_number != ""
                = @order.order_number.to_s
              - else
                = @order.id.to_s
          %br
          %br
          %span.order-table-label Number Of Items
          %span.order-table-info= @order.number_of_items
        %td.border-right{width: 120}
          %span.order-table-label Sale Date
          %span.order-table-info= @order.sale_date
          %br
          %br
          %span.order-table-label Ship Date
          %span.order-table-info
            - if @order.date_shipped
              = @order.date_shipped
            - else
              %span.red Not shipped yet
          %br
          %br
          %span.order-table-label Date Paid
          %span.order-table-info
            - if @order.date_paid
              = @order.date_paid
            - else
              %span.red Not paid yet
        %td.border-right
          %table
            %tr
              %td
                %strong Order Value
              %td.order-table-align-right= '$' + @order.order_value.to_s
            %tr
              %td 
                %span.secondary + Shipping
              %td.order-table-align-right
                %span.secondary= '+$' + @order.shipping.to_s
            %tr
              %td
                %span.secondary+ Sales Tax
              %td.order-table-align-right
                %span.secondary= '+$' + @order.sales_tax.to_s
            - if @order.inperson_discount
              %tr
                %td 
                  %span.secondary - In Person Discount
                %td.order-table-align-right
                  = '-$' +  @order.inperson_discount.to_s
            %tr.order-table-border-top
              %td 
                %strong Order Total
              %td.order-table-align-right
                = '$' +  @order.order_total.to_s
            %tr
              %td{width: 200}
                %span.secondary - Card Processing Fees
              %td.order-table-align-right
                %span.secondary= '-$' + @order.card_processing_fees.to_s
            %tr.order-table-border-top
              %td
                %strong Order Net
              %td.order-table-align-right.order-table-net= '$' + @order.order_net.to_s

        -if @order.adjusted_order_total
          %td
            %table
              %tr
                %td
                  %strong Order Value
                %td.order-table-align-right= '$' + @order.order_value.to_s
              %tr
                %td
                  %span.secondary - Sales Tax
                %td.order-table-align-right
                  %span.secondary= @order.refund
              - if @order.inperson_discount
                %tr.order-table-border-top
                  %td 
                    %strong In Person Discount
                  %td.order-table-align-right
                    = '$' +  @order.inperson_discount.to_s
              %tr.order-table-border-top
                %td 
                  %strong Order Total
                %td.order-table-align-right
                  = '$' +  @order.adjusted_order_total.to_s
              %tr
                %td
                  %span.secondary - Card Processing Fees
                %td.order-table-align-right
                  %span.secondary= '$' + @order.adjusted_card_processing_fees.to_s
              %tr.order-table-border-top
                %td
                  %strong Order Net
                %td.order-table-align-right.order-table-net= '$' + @order.adjusted_net_order_amount.to_s
        %td.border-right
          %span.order-table-label Promo Code
          %span.order-table-info
            - if @order.coupon_code != "" || @order.coupon_code != nil
              = @order.coupon_code
            - else
              None
          %br
          %br
          %span.secondary
            = @order.payment_method
            %br
            = @order.payment_type
            %br
            = @order.order_source
        %td
          %span.customer-table-label
            =link_to customer_url(@order.customer) do
              = @order.customer.first_name + " " + @order.customer.last_name
            - if @order.customer.company != ""
              %br
              = @order.customer.company
              %br
          %span.customer-table-info.secondary
            = "(" + @order.customer.etsy_username + ")"
            %br
          - if @order.customer.email
            %a{href: "mailto:" + @order.customer.email}
              = @order.customer.email
            %br
          - if @order.customer.instagram != "" || @order.customer.instagram != nil
            %a{href: "http://www.instagram.com/" + @order.customer.instagram.to_s, target: "_blank"}
              = "@" + @order.customer.instagram.to_s
            %br
        %td{width: 200}
          %span.customer-table-label Shipping Address
          %span.customer-table-info
            = @order.customer.ship_name
            %br
            = @order.customer.ship_address1
            %br
            - if @order.customer.ship_address2 != "" || !@order.customer.ship_address2.nil?
              = @order.customer.ship_address2
              %br
            = @order.customer.ship_city + ", " + @order.customer.ship_state + " " + @order.customer.ship_zipcode
            %br
            = @order.customer.ship_country




  .page-content-body-section
    %table#table-order-items.stripe.order-column
      %thead
        %tr
          %th Order Item ID

          %th Order Item
          %th Variation

          %th Quantity
          %th Price
          %th Coupon Discount

          %th Item Total

      %tbody
        - @order_items.each do |order_item|
          %tr
            %td.border-right
              =link_to edit_admin_order_item_url(order_item), target: "_blank" do
                = order_item.id
              = link_to edit_admin_order_item_url(order_item.product), target: "_blank" do
                %span.glyphicon.glyphicon-pencil.edit-icon
            %td
              = order_item.product.description
              = link_to edit_admin_product_url(order_item.product), target: "_blank" do
                %span.glyphicon.glyphicon-pencil.edit-icon
            %td.border-right
              - if order_item.variation
                = order_item.variation.variation_name

            %td= order_item.quantity
            %td= order_item.price
            %td.border-right= order_item.coupon_discount

            %td= order_item.item_total

          

:javascript
  $("#table-order-items").DataTable({
    dom: 'iCfrtS',
    pageLength: -1,
    order: [6, 'desc'],
    orderClasses: true
  });

app/views/orders/wholesale.html.haml
= render partial: 'orders', locals: {order_type: "Wholesale"}