config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'dashboard#version2'
  get 'dashboard2' => 'dashboard#index', as: :dashboard

  get 'upload' => 'upload#index', as: :upload

  resources :orders do
    collection { post :import_etsy }
    collection { post :import_square }
  end
  get 'wholesale_orders' => 'orders#wholesale', as: :wholesale

  resources :order_items do
    collection { post :import_etsy }
    collection { post :import_square }
  end

  resources :expenses do
    collection { post :import }
  end

  resources :products
  resources :customers
  resources :listings
  resources :variations
  resources :giveaways

end

app/views/layouts/_sidebar.html.haml
#sidebar
  %ul.nav.nav-pills.nav-stacked

    %li{class: current_page?(controller: 'orders', action: 'index') ? 'active' : ''}
      = link_to orders_path do
        %span.glyphicon.glyphicon-shopping-cart
        Retail
        -if get_incomplete_orders_count("Retail") > 0
          %span.sidebar-menu-item-count=get_incomplete_orders_count("Retail")

    %li{class: current_page?(controller: 'orders', action: 'wholesale') ? 'active' : ''}
      = link_to wholesale_path do
        %span.glyphicon.glyphicon-shopping-cart
        Wholesale
        -if get_incomplete_orders_count("Wholesale") > 0
          %span.sidebar-menu-item-count=get_incomplete_orders_count("Wholesale")

    %li{class: current_page?(controller: 'order_items', action: 'index') ? 'active' : ''}
      = link_to order_items_path do
        %span.glyphicon.glyphicon-th-list
        Fulfillment

    %br

    %li{class: current_page?(controller: 'products', action: 'index') ? 'active' : ''}
      = link_to products_path do
        %span.glyphicon.glyphicon-th-large
        Products
        %span.sidebar-menu-item-subtitle What do I design next?
  
    %li{class: current_page?(controller: 'customers', action: 'index') ? 'active' : ''}
      = link_to customers_path do
        %span.glyphicon.glyphicon-user
        Customers
        %span.sidebar-menu-item-subtitle How do I acquire more?

    %li{class: current_page?(controller: 'expenses', action: 'index') ? 'active' : ''}
      = link_to expenses_path do
        %span.glyphicon.glyphicon-usd
        Expenses
        %span.sidebar-menu-item-subtitle Where can I cut costs?

    %li{class: current_page?(controller: 'giveaways', action: 'index') ? 'active' : ''}
      = link_to giveaways_path do
        %span.glyphicon.glyphicon-gift
        Giveaways
        %span.sidebar-menu-item-subtitle Are giveaways working?

    -# %li{class: current_page?(controller: 'listings', action: 'index') ? 'active' : ''}
    -#   = link_to listings_path do
    -#     %span.glyphicon.glyphicon-th
    -#     Listings

    %br

    %li{class: current_page?(controller: 'upload', action: 'index') ? 'active' : ''}
      = link_to upload_path do
        %span.glyphicon.glyphicon-plus
        Upload Files

    %br

    %li{class: current_page?(controller: 'orders', action: 'new') ? 'active' : ''}
      = link_to new_order_path do
        %span.glyphicon.glyphicon-plus
        New Order

    %li{class: current_page?(controller: 'order_items', action: 'new') ? 'active' : ''}
      = link_to new_order_item_path do
        %span.glyphicon.glyphicon-plus
        New Order Item

    %br

    %li{class: current_page?(controller: 'expenses', action: 'new') && params[:expense_type] == 'Shipping' ? 'active' : ''}
      = link_to new_expense_path + '?name=Shipping&expense_type=Shipping&vendor=USPS' do
        %span.glyphicon.glyphicon-plus
        New Shipping
    %li{class: current_page?(controller: 'expenses', action: 'new') && params[:expense_type] == 'Materials' && params[:vendor] == 'Amazon' ? 'active' : ''}
      = link_to new_expense_path + '?name=&expense_type=Materials&vendor=Amazon' do
        %span.glyphicon.glyphicon-plus
        New Materials
    %li{class: current_page?(controller: 'expenses', action: 'new') && params[:vendor] == 'Redbubble' ? 'active' : ''}
      = link_to new_expense_path + '?name=&expense_type=Materials&vendor=Redbubble' do
        %span.glyphicon.glyphicon-plus
        New Redbubble
    %li{class: current_page?(controller: 'expenses', action: 'new') && !params[:expense_type] ? 'active' : ''}
      = link_to new_expense_path do
        %span.glyphicon.glyphicon-plus
        New Expense
    %br

    %li{class: current_page?(controller: 'giveaways', action: 'new') ? 'active' : ''}
      = link_to new_admin_giveaway_path do
        %span.glyphicon.glyphicon-plus
        New Giveaway

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wonton In A Million - Analytics
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags

    = favicon_link_tag 'favicon.ico'

    %script(src="http://code.highcharts.com/highcharts.js")

  %body

    #wrapper
      #sidebar-wrapper
        = render 'layouts/sidebar'
      #page-content-wrapper
        = render 'layouts/header'
        .page-content
          .container-fluid
            .row
              .col-md-12
                - if !flash.empty?
                  #alerts
                    - flash.each do |key, value|
                      =value
                = yield